import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Quicksand } from "next/font/google";
import clsx from "clsx";

const quicksand = Quicksand({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={clsx(quicksand.className, "width-full antialiased")}
      >
        {children}
      </body>
    </html>
  );
}
